# SPDX-License-Identifier: Apache-2.0
"""Clean, deterministic format fixtures for public-contract tests."""

from __future__ import annotations

from pathlib import Path

import cv2
import numpy as np
import zxingcpp

from codarascan import FormatInfo

ROOT = Path(__file__).resolve().parents[1]
QR_MODEL_1 = (
    ROOT / "third_party/zxing-cpp/test/samples/qrcode-2/qr-model-1.png"
)

# The installed ZXing writer supplies every public readable format except QR
# Model 1 and its semantic ISBN view. QR Model 1 uses ZXing-C++'s Apache-2.0
# black-box fixture at the repository's pinned submodule revision. ISBN is
# generated by the ISBN writer and selected through its underlying EAN-13
# reader, as required by ZXing-C++'s own API.
SAMPLES = {
    "codabar": "A123B",
    "code-128": "CODE128",
    "code-32": "01234567",
    "code-39": "CODE39",
    "code-39-extended": "Code39!",
    "code-39-standard": "CODE39",
    "code-93": "CODE93",
    "databar": "0950110153000",
    "databar-expanded": "(01)09501101530003",
    "databar-expanded-stacked": "(01)09501101530003",
    "databar-limited": "0950110153000",
    "databar-omni": "0950110153000",
    "databar-stacked": "0950110153000",
    "databar-stacked-omni": "0950110153000",
    "dx-film-edge": "77-2",
    "ean-13": "5901234123457",
    "ean-8": "12345670",
    "ean-upc": "5901234123457",
    "isbn": "9780306406157",
    "itf": "123456",
    "itf-14": "1234567890123",
    "pzn": "1234567",
    "telepen": "ABC123",
    "telepen-alpha": "ABC123",
    "telepen-numeric": "123456",
    "upc-a": "123456789012",
    "upc-e": "12345670",
    "aztec": "CODARASCAN",
    "aztec-code": "CODARASCAN",
    "aztec-rune": "123",
    "compact-pdf417": "CODARASCAN",
    "data-matrix": "CODARASCAN",
    "maxicode": "CODARASCAN",
    "micro-pdf417": "CODARASCAN",
    "micro-qr-code": "CODARA",
    "pdf417": "CODARASCAN",
    "qr-code": "CODARASCAN",
    "qr-code-model-2": "CODARASCAN",
    "rmqr-code": "CODARASCAN",
}


def _enum_for(label: str) -> zxingcpp.BarcodeFormat:
    return next(
        value
        for name, value in vars(zxingcpp.BarcodeFormat).items()
        if not name.startswith("_")
        and isinstance(value, zxingcpp.BarcodeFormat)
        and str(value) == label
    )


def clean_fixture(info: FormatInfo) -> tuple[np.ndarray, bytes]:
    if info.name == "qr-code-model-1":
        image = cv2.imread(str(QR_MODEL_1), cv2.IMREAD_GRAYSCALE)
        if image is None:
            raise RuntimeError(
                "the pinned ZXing-C++ QR Model 1 fixture is unavailable; "
                "initialize third_party/zxing-cpp"
            )
        expected = zxingcpp.read_barcode(
            image,
            formats=zxingcpp.barcode_formats_from_str(info.zxing_name),
        )
    else:
        barcode = zxingcpp.create_barcode(SAMPLES[info.name], _enum_for(info.zxing_name))
        image = np.asarray(
            zxingcpp.write_barcode_to_image(
                barcode,
                scale=8 if info.kind.value == "1d" else 6,
                add_quiet_zones=True,
            )
        ).copy()
        expected = zxingcpp.read_barcode(
            image,
            formats=(
                zxingcpp.BarcodeFormat.EAN13
                if info.name == "isbn"
                else zxingcpp.barcode_formats_from_str(info.zxing_name)
            ),
        )
    if expected is None:
        raise AssertionError(f"ZXing could not read its clean {info.name} fixture")
    return image, bytes(expected.bytes)
